// The course.
//
// Malay written in the Latin alphabet, as spoken in Singapore and Malaysia.
// There is no writing system to learn, so the whole course is the spoken
// language: words, whole phrases, and how the phrases are put together.
//
// Units are in teaching order. Each one carries
//   words    - [malay, english]                   the building blocks
//   phrases  - [malay, english, literal, note]    things you can actually say
//   note     - how this corner of the language works, in plain English
//
// `literal` is the word-for-word reading. It is there because Malay often puts
// things in a different order from English - "rumah saya" is "house my" - and
// seeing that once is worth more than being told it ten times. Where a phrase
// reads straight across, the literal is left empty.

var UNITS = [

/* ============================================================== 1. ASAS */
{
  id: 'asas',
  name: 'First words',
  malay: 'Asas',
  sub: 'Yes, no, thank you - the handful you cannot do without',
  note: 'Malay has no word for is, am or are. "Saya lapar" is literally ' +
        '"I hungry", and that is a complete, correct sentence - nothing is ' +
        'missing. There is no "a" or "the" either, and verbs never change ' +
        'shape: saya makan, awak makan, dia makan. One form, always.',
  words: [
    ['ya', 'yes'],
    ['tidak', 'no / not (full form)'],
    ['tak', 'no / not (what people actually say)'],
    ['bukan', 'not (for nouns - see Sentences)'],
    ['terima kasih', 'thank you'],
    ['sama-sama', 'you are welcome'],
    ['tolong', 'please / help'],
    ['maaf', 'sorry / excuse me'],
    ['minta maaf', 'I apologise'],
    ['boleh', 'can / may'],
    ['tak boleh', 'cannot'],
    ['ada', 'have / there is'],
    ['tiada', 'there is none'],
    ['takde', 'have not got (spoken)'],
    ['nak', 'want to (spoken)'],
    ['hendak', 'want to (full form)'],
    ['mahu', 'want'],
    ['tak nak', 'do not want'],
    ['saya', 'I / me'],
    ['awak', 'you (casual)'],
    ['dia', 'he / she'],
    ['ini', 'this'],
    ['itu', 'that'],
    ['apa', 'what'],
    ['siapa', 'who'],
    ['mana', 'where'],
    ['bila', 'when'],
    ['kenapa', 'why'],
    ['macam mana', 'how'],
    ['berapa', 'how much / how many'],
    ['baik', 'good / fine / alright'],
    ['bagus', 'good / great'],
    ['betul', 'correct / true'],
    ['salah', 'wrong'],
    ['sikit', 'a little'],
    ['banyak', 'a lot / many'],
    ['lagi', 'more / again / still'],
    ['juga', 'also / too'],
    ['sudah', 'already'],
    ['dah', 'already (spoken)'],
    ['belum', 'not yet'],
    ['jangan', 'do not'],
    ['sila', 'please (inviting)'],
    ['saja', 'only / just'],
    ['sekejap', 'a moment']
  ],
  phrases: [
    ['Terima kasih.', 'Thank you.', '', ''],
    ['Terima kasih banyak-banyak.', 'Thank you very much.', 'thank you many-many', 'Doubling a word makes it bigger, or plural. It is the closest thing Malay has to -s and to "very".'],
    ['Sama-sama.', 'You are welcome.', 'same-same', ''],
    ['Maaf.', 'Sorry. / Excuse me.', '', 'Apologising and getting past someone. Both jobs, one word.'],
    ['Tak apa.', 'It is alright. / Never mind.', 'not what', 'The everyday reply to an apology. Shortened further to takpe.'],
    ['Ya, boleh.', 'Yes, that works.', 'yes can', ''],
    ['Tak boleh.', 'Cannot.', '', ''],
    ['Saya tak tahu.', 'I do not know.', 'I not know', ''],
    ['Saya tak faham.', 'I do not understand.', 'I not understand', 'Worth learning before anything else. It buys you a slower repeat.'],
    ['Boleh ulang?', 'Could you say that again?', 'can repeat', ''],
    ['Tolong cakap perlahan sikit.', 'Please speak a little slower.', 'please speak slow a-little', ''],
    ['Apa ini?', 'What is this?', 'what this', ''],
    ['Tolong!', 'Help!', '', ''],
    ['Sekejap.', 'One moment.', '', 'Also kejap or jap in speech. The universal hang on.'],
    ['Sila duduk.', 'Please sit down.', 'please sit', ''],
    ['Jangan risau.', 'Do not worry.', 'do-not worry', ''],
    ['Betul ke?', 'Really?', 'true is-it', 'Adding ke turns a statement into a question.'],
    ['Saya nak ini.', 'I want this one.', 'I want this', 'Point at it. A complete transaction in three words.'],
    ['Tak nak, terima kasih.', 'No thanks.', 'not-want thank you', ''],
    ['Boleh tolong saya?', 'Can you help me?', 'can help me', ''],
    ['Sudah.', 'Done. / Already.', '', 'On its own it means that is finished, sorted.'],
    ['Belum lagi.', 'Not yet.', 'not-yet still', '']
  ]
},

/* ============================================================= 2. SALAM */
{
  id: 'salam',
  name: 'Greetings',
  malay: 'Salam',
  sub: 'Hello, goodbye, and how are you',
  note: 'Selamat means safe or blessed, and it opens nearly every greeting - ' +
        'selamat pagi, selamat jalan, selamat datang. Learn selamat plus a ' +
        'handful of nouns and the whole day is covered.',
  words: [
    ['selamat', 'safe / blessed'],
    ['pagi', 'morning'],
    ['tengah hari', 'midday'],
    ['petang', 'afternoon / early evening'],
    ['malam', 'night'],
    ['hai', 'hi'],
    ['helo', 'hello'],
    ['apa khabar', 'how are you'],
    ['khabar', 'news'],
    ['sihat', 'healthy / well'],
    ['jumpa', 'meet'],
    ['datang', 'come'],
    ['pergi', 'go'],
    ['jalan', 'walk / road / journey'],
    ['tinggal', 'stay / live'],
    ['balik', 'go back / go home'],
    ['sampai', 'arrive / until'],
    ['nanti', 'later'],
    ['esok', 'tomorrow'],
    ['gembira', 'happy / glad'],
    ['kenal', 'to know (a person)'],
    ['lama', 'a long time'],
    ['baru', 'new / just now'],
    ['dulu', 'first / previously'],
    ['hati-hati', 'take care / careful'],
    ['kawan', 'friend']
  ],
  phrases: [
    ['Selamat pagi.', 'Good morning.', 'blessed morning', 'Until about midday.'],
    ['Selamat tengah hari.', 'Good afternoon.', 'blessed middle day', 'Roughly midday to 2pm.'],
    ['Selamat petang.', 'Good afternoon / evening.', 'blessed late-afternoon', 'From about 2pm until dark.'],
    ['Selamat malam.', 'Good evening. / Good night.', 'blessed night', ''],
    ['Selamat datang.', 'Welcome.', 'blessed coming', 'On every shop door you will ever walk through.'],
    ['Selamat jalan.', 'Safe journey. / Goodbye.', 'blessed journey', 'Said to the one leaving.'],
    ['Selamat tinggal.', 'Goodbye.', 'blessed staying', 'Said by the one leaving, to the one staying. Fairly final.'],
    ['Apa khabar?', 'How are you?', 'what news', ''],
    ['Khabar baik.', 'I am well.', 'news good', 'The standard answer, usually with terima kasih after it.'],
    ['Baik-baik saja.', 'Just fine.', 'good-good only', ''],
    ['Awak macam mana?', 'And you?', 'you how', ''],
    ['Lama tak jumpa.', 'Long time no see.', 'long not meet', ''],
    ['Jumpa lagi.', 'See you again.', 'meet again', 'The everyday goodbye. Warmer than selamat tinggal.'],
    ['Jumpa esok.', 'See you tomorrow.', 'meet tomorrow', ''],
    ['Jumpa nanti.', 'See you later.', 'meet later', ''],
    ['Saya nak balik dulu.', 'I will head off now.', 'I want return first', 'dulu softens a departure - I will go on ahead.'],
    ['Hati-hati.', 'Take care.', 'careful-careful', 'Said as someone leaves.'],
    ['Gembira jumpa awak.', 'Good to see you.', 'glad meet you', ''],
    ['Apa cerita?', 'What is up?', 'what story', 'Casual, between friends.'],
    ['Sihat?', 'Keeping well?', 'healthy', 'A one-word greeting. Answer sihat back.'],
    ['Mari masuk.', 'Come in.', 'come enter', ''],
    ['Jom.', 'Let us go.', '', 'One syllable, endlessly useful. Jom makan, jom balik, jom.']
  ]
},

/* =========================================================== 3. KENALAN */
{
  id: 'kenalan',
  name: 'Meeting people',
  malay: 'Kenalan',
  sub: 'Your name, where you are from, and small talk',
  note: 'Malay marks respect by what you call someone, not by changing the ' +
        'verb. A stranger a little older is abang (older brother) or kakak ' +
        '(older sister), shortened to bang and kak. Much older is pakcik ' +
        '(uncle) or makcik (auntie). Using these instead of awak is the ' +
        'single easiest way to sound like you belong here.',
  words: [
    ['nama', 'name'],
    ['encik', 'Mr / sir'],
    ['puan', 'Mrs / madam'],
    ['cik', 'Miss'],
    ['abang', 'older brother / young man'],
    ['kakak', 'older sister / young woman'],
    ['adik', 'younger sibling / a younger person'],
    ['pakcik', 'uncle / older man'],
    ['makcik', 'auntie / older woman'],
    ['orang', 'person / people'],
    ['negara', 'country'],
    ['asal', 'origin'],
    ['dari', 'from'],
    ['di', 'at / in'],
    ['sini', 'here'],
    ['sana', 'there'],
    ['kerja', 'work / job'],
    ['belajar', 'study / learn'],
    ['umur', 'age'],
    ['tahun', 'year'],
    ['cakap', 'speak / say'],
    ['bahasa', 'language'],
    ['Melayu', 'Malay'],
    ['Inggeris', 'English'],
    ['sedikit', 'a little'],
    ['pandai', 'clever / good at'],
    ['suka', 'like'],
    ['kenalkan', 'let me introduce'],
    ['tanya', 'ask'],
    ['tahu', 'know (a fact)']
  ],
  phrases: [
    ['Siapa nama awak?', 'What is your name?', 'who name your', 'Malay asks who is your name, not what.'],
    ['Nama saya Ben.', 'My name is Ben.', 'name my Ben', 'Possessives go after the noun: nama saya, rumah saya, kereta saya.'],
    ['Awak dari mana?', 'Where are you from?', 'you from where', ''],
    ['Saya dari Singapura.', 'I am from Singapore.', '', ''],
    ['Saya orang Singapura.', 'I am Singaporean.', 'I person Singapore', ''],
    ['Awak tinggal di mana?', 'Where do you live?', 'you live at where', ''],
    ['Saya tinggal di Bishan.', 'I live in Bishan.', '', ''],
    ['Awak kerja apa?', 'What do you do?', 'you work what', ''],
    ['Saya kerja di pejabat.', 'I work in an office.', '', ''],
    ['Berapa umur awak?', 'How old are you?', 'how-much age your', ''],
    ['Umur saya tiga puluh tahun.', 'I am thirty.', 'age my three ten year', 'Never tahun-tahun. A number already tells you it is plural.'],
    ['Saya belajar bahasa Melayu.', 'I am learning Malay.', 'I study language Malay', ''],
    ['Saya cakap sedikit saja.', 'I only speak a little.', 'I speak little only', 'The most useful sentence here. It resets their speed.'],
    ['Awak boleh cakap Inggeris?', 'Do you speak English?', 'you can speak English', ''],
    ['Bahasa Melayu awak bagus!', 'Your Malay is good!', 'language Malay your good', ''],
    ['Belum bagus lagi.', 'Not good yet.', 'not-yet good still', 'The modest reply, and the expected one.'],
    ['Kenalkan, ini kawan saya.', 'This is my friend.', 'introduce, this friend my', ''],
    ['Boleh saya tahu nama awak?', 'May I ask your name?', 'may I know name your', 'Politer than the bare question.'],
    ['Maaf bang, boleh tanya?', 'Excuse me, can I ask something?', 'sorry brother, can ask', 'How to open with a stranger at a stall or in the street.'],
    ['Saya baru sampai sini.', 'I have just arrived here.', 'I just arrive here', ''],
    ['Awak orang mana?', 'Where are you from?', 'you person where', 'More casual than dari mana.'],
    ['Saya tinggal di sini lima tahun.', 'I have lived here five years.', 'I live at here five year', 'No past tense needed. The five years does that work.']
  ]
},

/* ============================================================ 4. NOMBOR */
{
  id: 'nombor',
  name: 'Numbers',
  malay: 'Nombor',
  sub: 'Counting, and the belas / puluh trap',
  note: 'Malay numbers are built, not memorised. Learn one to nine, then four ' +
        'endings: belas is the teens, puluh is the tens, ratus is hundreds, ' +
        'ribu is thousands. lima belas is 15, lima puluh is 50. That one pair ' +
        'of syllables is the difference between five dollars and fifty, and it ' +
        'is the thing to drill until it is automatic. se- at the front means ' +
        'one: sepuluh, seratus, seribu - never satu puluh.',
  words: [
    ['kosong', 'zero'],
    ['satu', 'one'],
    ['dua', 'two'],
    ['tiga', 'three'],
    ['empat', 'four'],
    ['lima', 'five'],
    ['enam', 'six'],
    ['tujuh', 'seven'],
    ['lapan', 'eight'],
    ['sembilan', 'nine'],
    ['sepuluh', 'ten'],
    ['sebelas', 'eleven'],
    ['dua belas', 'twelve'],
    ['lima belas', 'fifteen'],
    ['dua puluh', 'twenty'],
    ['dua puluh lima', 'twenty-five'],
    ['tiga puluh', 'thirty'],
    ['empat puluh', 'forty'],
    ['lima puluh', 'fifty'],
    ['enam puluh', 'sixty'],
    ['tujuh puluh', 'seventy'],
    ['lapan puluh', 'eighty'],
    ['sembilan puluh', 'ninety'],
    ['seratus', 'one hundred'],
    ['dua ratus', 'two hundred'],
    ['seribu', 'one thousand'],
    ['sepuluh ribu', 'ten thousand'],
    ['sejuta', 'one million'],
    ['setengah', 'half'],
    ['suku', 'a quarter'],
    ['nombor', 'number'],
    ['kali', 'times / occasion'],
    ['pertama', 'first'],
    ['kedua', 'second'],
    ['terakhir', 'last'],
    ['kira', 'count / reckon'],
    ['jumlah', 'total'],
    ['lebih', 'more than / over'],
    ['kurang', 'less than / under'],
    ['dalam', 'about / around (of a number)'],
    ['perpuluhan', 'decimal point (proper form)'],
    ['titik', 'point / dot (spoken)'],
    ['koma', 'comma (Indonesian decimal point)'],
    ['kosong kosong', 'point zero zero / .00']
  ],
  phrases: [
    ['Berapa?', 'How many? / How much?', '', 'On its own, in any context. The workhorse question.'],
    ['Satu, dua, tiga.', 'One, two, three.', '', ''],
    ['Lima belas, bukan lima puluh.', 'Fifteen, not fifty.', 'five teen, not five ten', 'Say this back when you are not sure. They will confirm it.'],
    ['Dua puluh tiga.', 'Twenty-three.', 'two ten three', 'Tens first, then the unit. Same order as English.'],
    ['Seratus lima puluh.', 'A hundred and fifty.', 'one-hundred five ten', ''],
    ['Dua ribu lima ratus.', 'Two thousand five hundred.', 'two thousand five hundred', ''],
    ['Nombor telefon saya kosong sembilan satu...', 'My phone number is 091...', 'number telephone my zero nine one', 'Phone numbers are read digit by digit, and 0 is kosong.'],
    ['Berapa banyak?', 'How many?', 'how-much many', ''],
    ['Banyak mana?', 'How much of it?', 'many where', ''],
    ['Saya nak dua.', 'I want two.', 'I want two', 'No word for "of them" is needed.'],
    ['Dua saja.', 'Just two.', 'two only', ''],
    ['Tambah satu lagi.', 'One more, please.', 'add one more', ''],
    ['Kurang satu.', 'One short.', 'less one', ''],
    ['Setengah jam.', 'Half an hour.', 'half hour', ''],
    ['Dalam sepuluh minit.', 'In about ten minutes.', 'within ten minute', ''],
    ['Boleh ulang nombor tu?', 'Can you repeat that number?', 'can repeat number that', 'The single most useful line in this whole unit.'],
    ['Lima belas ke lima puluh?', 'Fifteen or fifty?', 'five-teen or five-ten', 'Ask it outright. Nobody minds.'],
    ['Tiga orang.', 'Three people.', 'three person', 'orang is the counter for people, and it never goes plural.'],
    ['Kali pertama saya datang sini.', 'It is my first time here.', 'time first I come here', ''],
    ['Kira sekali.', 'Add it all together.', 'count at-once', 'At a stall, when you want one total for everything.'],
    ['Tiga perpuluhan lima.', 'Three point five. (3.5)', 'three decimal five', 'The proper way to read a decimal that is not money - a weight, a percentage, a rating.'],
    ['Tiga titik lima.', 'Three point five. (3.5)', 'three dot five', 'How people actually say it out loud.'],
    ['Dua perpuluhan tujuh lima.', 'Two point seven five. (2.75)', 'two decimal seven five', 'After the point, digits are read one at a time: tujuh, lima - not seventy-five.'],
    ['Sifar perpuluhan lima.', 'Zero point five. (0.5)', 'zero decimal five', 'sifar is the written zero. Spoken, kosong is far more common.'],
    ['Berat dua koma lima kilo.', 'It weighs 2.5 kilos.', 'weight two comma five kilo', 'koma is the Indonesian reading - you will hear it in imported labelling.'],
    ['Lapan puluh lima peratus.', 'Eighty-five per cent.', 'eight ten five per-cent', '']
  ]
},

/* ============================================================== 5. DUIT */
{
  id: 'duit',
  name: 'Money and paying',
  malay: 'Duit',
  sub: 'Prices, paying, change - and catching the figure they said',
  note: 'The hard part of paying is not speaking, it is hearing. A price ' +
        'arrives fast and unstressed, and there is no decimal point in it - ' +
        'the currency word is the point. Everything before ringgit or dolar ' +
        'is dollars, everything after is cents: lima ringgit lima puluh sen ' +
        'is 5.50. Then the shortcuts start. sen gets dropped, so lima lima ' +
        'puluh is still 5.50. setengah (half) stands in for fifty, so lima ' +
        'setengah is 5.50 as well - three ways to say one price. Two traps ' +
        'are worth drilling on their own. Cents under ten keep their small ' +
        'number, so lima ringgit lima sen is 5.05, and if the ringgit gets ' +
        'swallowed it sounds like plain five. And belas versus puluh bites ' +
        'again down in the cents: lima belas sen is 15c, lima puluh sen is ' +
        '50c. When in doubt, say the figure back with the currency put in - ' +
        'lima ringgit lima puluh sen? - and they will just say ya. The ' +
        'Numbers drill on the home screen is built for exactly this.',
  words: [
    ['duit', 'money (everyday)'],
    ['wang', 'money (formal)'],
    ['harga', 'price'],
    ['ringgit', 'ringgit (Malaysia)'],
    ['dolar', 'dollar (Singapore)'],
    ['sen', 'cent'],
    ['bayar', 'pay'],
    ['tunai', 'cash'],
    ['kad', 'card'],
    ['kad kredit', 'credit card'],
    ['baki', 'change / balance'],
    ['duit kecil', 'small change'],
    ['duit syiling', 'coins'],
    ['resit', 'receipt'],
    ['mahal', 'expensive'],
    ['murah', 'cheap'],
    ['diskaun', 'discount'],
    ['potong', 'to cut (a price)'],
    ['jumlah', 'total'],
    ['semua', 'all'],
    ['semuanya', 'all of it / altogether'],
    ['sekali', 'at once / together'],
    ['asing-asing', 'separately'],
    ['belanja', 'to treat / spending'],
    ['percuma', 'free'],
    ['tukar', 'to change / exchange'],
    ['hutang', 'debt / owe'],
    ['pinjam', 'borrow'],
    ['simpan', 'keep'],
    ['cukup', 'enough'],
    ['tak cukup', 'not enough'],
    ['bank', 'bank'],
    ['mesin ATM', 'cash machine'],
    ['akaun', 'account'],
    ['bil', 'bill'],
    ['cukai', 'tax'],
    ['untung', 'profit'],
    ['naik harga', 'price has gone up'],
    ['turun harga', 'price has come down'],
    ['berbaloi', 'worth it']
  ],
  phrases: [
    ['Berapa harga ini?', 'How much is this?', 'how-much price this', 'The one to have ready before you open your mouth.'],
    ['Berapa semuanya?', 'How much altogether?', 'how-much all-of-it', 'At the end, for the total.'],
    ['Berapa satu?', 'How much each?', 'how-much one', ''],
    ['Berapa sekilo?', 'How much per kilo?', 'how-much one-kilo', ''],
    ['Dua ringgit lima puluh sen.', 'Two ringgit fifty cents.', 'two ringgit five ten cent', 'The full form. Most people will say less than this.'],
    ['Dua lima puluh.', 'Two fifty.', 'two five-ten', 'The same price, the way it is actually said. Currency and sen both dropped.'],
    ['Dua setengah.', 'Two fifty.', 'two half', 'And again - two and a half ringgit. All three mean RM2.50.'],
    ['Lima ringgit lima belas sen.', 'Five fifteen. (5.15)', 'five ringgit five-teen cent', 'Listen for belas. This is 5.15, not 5.50.'],
    ['Lima ringgit lima puluh sen.', 'Five fifty. (5.50)', 'five ringgit five-ten cent', 'And this is 5.50. One syllable apart from the line above.'],
    ['Lima ringgit lima sen.', 'Five oh five. (5.05)', 'five ringgit five cent', 'Cents under ten stay small. Drop the ringgit and it sounds like plain five.'],
    ['Sepuluh sembilan puluh.', 'Ten ninety. (10.90)', 'ten nine-ten', 'No currency word at all. Very common, and the fastest to mishear.'],
    ['Dua puluh ringgit tepat.', 'Twenty ringgit exactly.', 'two ten ringgit exact', 'tepat means the price is round - nothing after the point.'],
    ['Lima kosong kosong.', 'Five dollars even. (5.00)', 'five zero zero', 'Reading the .00 out loud, the way a till display looks.'],
    ['Satu ringgit sembilan puluh sembilan sen.', 'One ninety-nine. (1.99)', 'one ringgit nine-ten nine cent', ''],
    ['Maaf, lima belas ke lima puluh sen?', 'Sorry - fifteen or fifty cents?', 'sorry, five-teen or five-ten cent', 'Ask about the cents specifically. It narrows it down fast.'],
    ['Maaf, berapa tadi?', 'Sorry, how much was that?', 'sorry, how-much just-now', 'tadi means a moment ago. This is your rewind button.'],
    ['Lima belas ringgit ke lima puluh?', 'Fifteen ringgit or fifty?', 'five-teen ringgit or five-ten', 'Ask it flat out. It is a normal question.'],
    ['Boleh tulis harga?', 'Could you write the price down?', 'can write price', 'No shame in it, and it always works.'],
    ['Saya nak bayar.', 'I would like to pay.', 'I want pay', ''],
    ['Boleh bayar dengan kad?', 'Can I pay by card?', 'can pay with card', ''],
    ['Saya bayar tunai.', 'I will pay cash.', 'I pay cash', ''],
    ['Ada PayNow?', 'Do you take PayNow?', 'have PayNow', 'Swap in QR, PayLah or e-wallet as needed.'],
    ['Boleh scan QR?', 'Can I scan the QR code?', 'can scan QR', ''],
    ['Ini duit.', 'Here you are.', 'this money', 'Handing it over.'],
    ['Simpan baki.', 'Keep the change.', 'keep change', ''],
    ['Mana baki saya?', 'Where is my change?', 'where change my', ''],
    ['Baki lima ringgit.', 'Five ringgit change.', 'change five ringgit', 'What they say as they hand it back.'],
    ['Ada duit kecil?', 'Do you have small change?', 'have money small', ''],
    ['Maaf, saya takde duit kecil.', 'Sorry, I have no small notes.', 'sorry, I have-not money small', ''],
    ['Boleh bagi resit?', 'Could I have a receipt?', 'can give receipt', ''],
    ['Mahal sangat.', 'That is too expensive.', 'expensive very', ''],
    ['Boleh kurang sikit?', 'Can you come down a little?', 'can less a-little', 'The standard opener at a market. Not at a hawker stall.'],
    ['Boleh bagi diskaun?', 'Can you give a discount?', 'can give discount', ''],
    ['Kalau saya ambil dua?', 'What if I take two?', 'if I take two', 'The quiet way to ask for a better price.'],
    ['Harga terakhir berapa?', 'What is your best price?', 'price last how-much', ''],
    ['Tak cukup duit.', 'I do not have enough.', 'not enough money', ''],
    ['Saya bayar dulu.', 'Let me get this one.', 'I pay first', ''],
    ['Saya belanja.', 'It is on me.', 'I treat', ''],
    ['Kita bayar asing-asing.', 'Let us pay separately.', 'we pay separate-separate', ''],
    ['Bayar sekali.', 'All on one bill.', 'pay at-once', ''],
    ['Bayar di mana?', 'Where do I pay?', 'pay at where', ''],
    ['Bayar di kaunter.', 'Pay at the counter.', 'pay at counter', 'What you will be told.'],
    ['Ini percuma?', 'Is this free?', 'this free', ''],
    ['Harga dah naik.', 'The price has gone up.', 'price already rise', ''],
    ['Berbaloi tak?', 'Is it worth it?', 'worth-it not', 'Tacking tak on the end is how you ask a yes-or-no question.'],
    ['Boleh tukar duit di sini?', 'Can I change money here?', 'can change money at here', ''],
    ['Saya nak keluarkan duit.', 'I need to take out cash.', 'I want take-out money', ''],
    ['Kad saya tak boleh guna.', 'My card is not working.', 'card my not can use', '']
  ]
},

/* ============================================================= 6. MAKAN */
{
  id: 'makan',
  name: 'Food and drink',
  malay: 'Makan',
  sub: 'Ordering at a stall, and saying how you want it',
  note: 'Malay puts the describing word after the thing: nasi goreng is ' +
        'rice fried, air batu is water stone (ice), teh tarik is tea pulled. ' +
        'Once you notice that, a menu stops being a list to memorise and ' +
        'becomes a set of parts you can read. One word to learn before all ' +
        'others: bungkus, meaning wrap it up to take away.',
  words: [
    ['makan', 'eat / food'],
    ['minum', 'drink'],
    ['makanan', 'food'],
    ['minuman', 'drinks'],
    ['nasi', 'rice (cooked)'],
    ['mi', 'noodles'],
    ['roti', 'bread'],
    ['ayam', 'chicken'],
    ['daging', 'beef / meat'],
    ['ikan', 'fish'],
    ['udang', 'prawn'],
    ['telur', 'egg'],
    ['sayur', 'vegetables'],
    ['buah', 'fruit'],
    ['sup', 'soup'],
    ['kuah', 'gravy / sauce'],
    ['sambal', 'chilli paste'],
    ['cili', 'chilli'],
    ['garam', 'salt'],
    ['gula', 'sugar'],
    ['air', 'water / any drink'],
    ['air batu', 'ice'],
    ['teh', 'tea'],
    ['kopi', 'coffee'],
    ['susu', 'milk'],
    ['sejuk', 'cold'],
    ['panas', 'hot (temperature)'],
    ['pedas', 'spicy'],
    ['manis', 'sweet'],
    ['masin', 'salty'],
    ['masam', 'sour'],
    ['sedap', 'delicious'],
    ['kenyang', 'full'],
    ['lapar', 'hungry'],
    ['dahaga', 'thirsty'],
    ['bungkus', 'takeaway / to wrap'],
    ['makan sini', 'eat in'],
    ['halal', 'halal'],
    ['pinggan', 'plate'],
    ['gelas', 'glass'],
    ['sudu', 'spoon'],
    ['garpu', 'fork'],
    ['cuba', 'try'],
    ['pesan', 'to order'],
    ['tambah', 'add / extra'],
    ['besar', 'big'],
    ['kecil', 'small'],
    ['biasa', 'regular / usual']
  ],
  phrases: [
    ['Saya lapar.', 'I am hungry.', 'I hungry', 'No verb. Nothing is missing.'],
    ['Saya dahaga.', 'I am thirsty.', 'I thirsty', ''],
    ['Jom makan.', 'Let us eat.', 'lets eat', ''],
    ['Saya nak pesan.', 'I would like to order.', 'I want order', ''],
    ['Saya nak nasi ayam.', 'I would like chicken rice.', 'I want rice chicken', ''],
    ['Satu teh panas.', 'One hot tea.', 'one tea hot', 'A number, then the thing. That is a whole order.'],
    ['Dua kopi, satu teh.', 'Two coffees and one tea.', 'two coffee, one tea', ''],
    ['Bungkus.', 'To take away.', 'wrap', 'Say it at the end of the order. One word does the job.'],
    ['Makan sini.', 'Eating in.', 'eat here', ''],
    ['Kurang manis.', 'Less sweet.', 'less sweet', 'Standard at any drinks stall.'],
    ['Tanpa gula.', 'No sugar.', 'without sugar', ''],
    ['Tambah air batu.', 'With ice, please.', 'add ice', ''],
    ['Jangan pedas.', 'Not spicy, please.', 'do-not spicy', ''],
    ['Pedas sikit boleh.', 'A little spicy is fine.', 'spicy a-little can', ''],
    ['Pedas tak?', 'Is it spicy?', 'spicy not', ''],
    ['Ada yang tak pedas?', 'Is there anything not spicy?', 'have which not spicy', ''],
    ['Ini halal?', 'Is this halal?', 'this halal', ''],
    ['Saya tak makan daging.', 'I do not eat beef.', 'I not eat beef', ''],
    ['Saya tak makan daging babi.', 'I do not eat pork.', 'I not eat meat pig', ''],
    ['Ada sayur saja?', 'Do you have anything vegetarian?', 'have vegetable only', ''],
    ['Apa yang sedap di sini?', 'What is good here?', 'what which delicious at here', 'Ask this and you will be looked after.'],
    ['Awak cadang apa?', 'What do you recommend?', 'you suggest what', ''],
    ['Sedap!', 'Delicious!', '', 'Say it while eating. It lands every time.'],
    ['Sedap sangat.', 'Really delicious.', 'delicious very', ''],
    ['Saya dah kenyang.', 'I am full.', 'I already full', ''],
    ['Cukup, terima kasih.', 'That is enough, thank you.', 'enough, thank you', ''],
    ['Boleh tambah nasi?', 'Could I have more rice?', 'can add rice', ''],
    ['Tolong bagi air kosong.', 'Plain water, please.', 'please give water empty', 'air kosong is the plain water everyone asks for.'],
    ['Lama tak?', 'Will it be long?', 'long not', ''],
    ['Berapa lama nak tunggu?', 'How long is the wait?', 'how-much long want wait', ''],
    ['Meja untuk dua orang.', 'A table for two.', 'table for two person', ''],
    ['Boleh bagi bil?', 'Could I have the bill?', 'can give bill', '']
  ]
},

/* ============================================================== 7. BELI */
{
  id: 'beli',
  name: 'Shopping',
  malay: 'Beli-belah',
  sub: 'Asking for things, sizes, and haggling',
  note: 'Two verbs carry most of shopping: ada (there is, have you got) and ' +
        'boleh (can, may I). "Ada saiz besar?" and "Boleh cuba?" will get you ' +
        'through almost any shop. Malay makes a question out of a statement ' +
        'just by the way you say it - no word order changes at all.',
  words: [
    ['beli', 'buy'],
    ['jual', 'sell'],
    ['kedai', 'shop'],
    ['pasar', 'market'],
    ['pasar raya', 'supermarket'],
    ['barang', 'thing / goods'],
    ['saiz', 'size'],
    ['warna', 'colour'],
    ['merah', 'red'],
    ['biru', 'blue'],
    ['hijau', 'green'],
    ['kuning', 'yellow'],
    ['hitam', 'black'],
    ['putih', 'white'],
    ['baju', 'shirt / clothing'],
    ['seluar', 'trousers'],
    ['kasut', 'shoes'],
    ['beg', 'bag'],
    ['topi', 'hat'],
    ['cuba', 'try'],
    ['pakai', 'wear / use'],
    ['muat', 'to fit'],
    ['ketat', 'tight'],
    ['longgar', 'loose'],
    ['panjang', 'long'],
    ['pendek', 'short'],
    ['berat', 'heavy'],
    ['ringan', 'light'],
    ['baik', 'good quality'],
    ['rosak', 'broken / spoilt'],
    ['lain', 'other / different'],
    ['sama', 'same'],
    ['pilih', 'choose'],
    ['tengok', 'look / see'],
    ['tunjuk', 'show'],
    ['stok', 'stock'],
    ['habis', 'finished / sold out'],
    ['tutup', 'closed'],
    ['buka', 'open'],
    ['plastik', 'plastic bag']
  ],
  phrases: [
    ['Saya nak beli ini.', 'I want to buy this.', 'I want buy this', ''],
    ['Saya nak tengok saja.', 'I am just looking.', 'I want look only', 'The polite way to wave off help.'],
    ['Ada yang lain?', 'Do you have another one?', 'have which other', ''],
    ['Ada warna lain?', 'Do you have another colour?', 'have colour other', ''],
    ['Ada saiz besar?', 'Do you have a large?', 'have size big', ''],
    ['Ada saiz lebih kecil?', 'Do you have a smaller one?', 'have size more small', ''],
    ['Boleh saya cuba?', 'Can I try it on?', 'can I try', ''],
    ['Bilik cuba di mana?', 'Where is the fitting room?', 'room try at where', ''],
    ['Terlalu ketat.', 'It is too tight.', 'too tight', 'ter- in front of a word means too much of it.'],
    ['Tak muat.', 'It does not fit.', 'not fit', ''],
    ['Boleh tunjuk yang itu?', 'Could you show me that one?', 'can show which that', ''],
    ['Yang ini berapa?', 'How much is this one?', 'which this how-much', ''],
    ['Ada stok?', 'Is it in stock?', 'have stock', ''],
    ['Dah habis.', 'It is sold out.', 'already finished', 'What you will be told.'],
    ['Bila ada lagi?', 'When will you have more?', 'when have again', ''],
    ['Ini buatan mana?', 'Where is this made?', 'this made where', ''],
    ['Ada jaminan?', 'Is there a warranty?', 'have guarantee', ''],
    ['Boleh pulangkan?', 'Can I return it?', 'can return', ''],
    ['Barang ini rosak.', 'This one is damaged.', 'thing this broken', ''],
    ['Boleh tukar?', 'Can I exchange it?', 'can change', ''],
    ['Tolong bungkus.', 'Please wrap it up.', 'please wrap', ''],
    ['Tak payah plastik.', 'No bag, thanks.', 'no-need plastic', ''],
    ['Kedai tutup pukul berapa?', 'What time do you close?', 'shop close hour how-much', ''],
    ['Saya fikir dulu.', 'Let me think about it.', 'I think first', 'The graceful exit from a hard sell.'],
    ['Saya datang lagi nanti.', 'I will come back later.', 'I come again later', '']
  ]
},

/* ============================================================= 8. JALAN */
{
  id: 'jalan',
  name: 'Getting around',
  malay: 'Jalan',
  sub: 'Taxis, buses, trains and directions',
  note: 'kiri is left, kanan is right, terus is straight on. Those three plus ' +
        'sini (here) will get you anywhere in a taxi. Note that kereta is a ' +
        'car in Malaysia and Singapore, but a train in Indonesia - one of the ' +
        'few words that genuinely trips people up across the causeway.',
  words: [
    ['pergi', 'go'],
    ['datang', 'come'],
    ['sampai', 'arrive'],
    ['jalan', 'road / to walk'],
    ['jalan kaki', 'to go on foot'],
    ['kereta', 'car'],
    ['teksi', 'taxi'],
    ['bas', 'bus'],
    ['keretapi', 'train'],
    ['MRT', 'MRT'],
    ['stesen', 'station'],
    ['perhentian bas', 'bus stop'],
    ['lapangan terbang', 'airport'],
    ['kapal terbang', 'aeroplane'],
    ['basikal', 'bicycle'],
    ['motosikal', 'motorbike'],
    ['kiri', 'left'],
    ['kanan', 'right'],
    ['terus', 'straight on'],
    ['pusing', 'turn'],
    ['berhenti', 'stop'],
    ['tunggu', 'wait'],
    ['dekat', 'near'],
    ['jauh', 'far'],
    ['depan', 'in front'],
    ['belakang', 'behind'],
    ['sebelah', 'next to'],
    ['atas', 'above / upstairs'],
    ['bawah', 'below / downstairs'],
    ['simpang', 'junction'],
    ['lampu isyarat', 'traffic lights'],
    ['jem', 'traffic jam'],
    ['laju', 'fast'],
    ['perlahan', 'slow'],
    ['peta', 'map'],
    ['alamat', 'address'],
    ['tiket', 'ticket'],
    ['tambang', 'fare'],
    ['naik', 'to board / go up'],
    ['turun', 'to get off / go down'],
    ['pintu', 'door'],
    ['sesat', 'lost']
  ],
  phrases: [
    ['Saya nak pergi ke Bishan.', 'I want to go to Bishan.', 'I want go to Bishan', ''],
    ['Tolong ke alamat ini.', 'To this address, please.', 'please to address this', 'Show them the phone as you say it.'],
    ['Berapa tambang?', 'How much is the fare?', 'how-much fare', ''],
    ['Guna meter boleh?', 'Can you use the meter?', 'use meter can', ''],
    ['Berhenti di sini.', 'Stop here.', 'stop at here', ''],
    ['Berhenti depan sana.', 'Stop just up there.', 'stop front there', ''],
    ['Belok kiri.', 'Turn left.', 'turn left', ''],
    ['Belok kanan.', 'Turn right.', 'turn right', ''],
    ['Terus saja.', 'Straight on.', 'straight only', ''],
    ['Di simpang depan, belok kanan.', 'Turn right at the next junction.', 'at junction front, turn right', ''],
    ['Jauh tak dari sini?', 'Is it far from here?', 'far not from here', ''],
    ['Dekat saja.', 'It is close by.', 'near only', ''],
    ['Boleh jalan kaki?', 'Can I walk there?', 'can walk foot', ''],
    ['Berapa lama nak sampai?', 'How long will it take?', 'how-much long want arrive', ''],
    ['Jalan mana ke stesen?', 'Which way to the station?', 'road which to station', ''],
    ['Stesen MRT di mana?', 'Where is the MRT station?', 'station MRT at where', ''],
    ['Bas nombor berapa?', 'Which bus number?', 'bus number how-much', ''],
    ['Bas ini pergi ke bandar?', 'Does this bus go into town?', 'bus this go to town', ''],
    ['Saya nak turun sini.', 'I want to get off here.', 'I want descend here', ''],
    ['Saya turun stesen depan.', 'I am getting off at the next stop.', 'I descend station front', ''],
    ['Tolong beritahu bila sampai.', 'Please tell me when we get there.', 'please tell when arrive', ''],
    ['Saya sesat.', 'I am lost.', 'I lost', ''],
    ['Saya tak tahu jalan.', 'I do not know the way.', 'I not know road', ''],
    ['Boleh tunjuk di peta?', 'Can you show me on the map?', 'can show at map', ''],
    ['Jem teruk hari ini.', 'The traffic is terrible today.', 'jam bad day this', ''],
    ['Tolong cepat sikit.', 'A bit quicker, please.', 'please fast a-little', ''],
    ['Tak payah cepat.', 'No rush.', 'no-need fast', ''],
    ['Tunggu sekejap.', 'Wait a moment.', 'wait a-moment', ''],
    ['Saya sampai dah.', 'I have arrived.', 'I arrive already', ''],
    ['Tempat letak kereta di mana?', 'Where can I park?', 'place put car at where', '']
  ]
},

/* ============================================================ 9. TEMPAT */
{
  id: 'tempat',
  name: 'Places',
  malay: 'Tempat',
  sub: 'Finding the shop, the toilet, the bank',
  note: 'di means at or in, ke means to, dari means from. Three little words, ' +
        'and between them they handle every question about where something is ' +
        'or where you are headed. "Di mana tandas?" - at where toilet - is ' +
        'the one to have ready at all times.',
  words: [
    ['tempat', 'place'],
    ['rumah', 'house / home'],
    ['kedai', 'shop'],
    ['pejabat', 'office'],
    ['sekolah', 'school'],
    ['hospital', 'hospital'],
    ['klinik', 'clinic'],
    ['farmasi', 'pharmacy'],
    ['balai polis', 'police station'],
    ['bank', 'bank'],
    ['pasar', 'market'],
    ['restoran', 'restaurant'],
    ['hotel', 'hotel'],
    ['masjid', 'mosque'],
    ['tandas', 'toilet'],
    ['bilik', 'room'],
    ['tingkat', 'floor / storey'],
    ['lif', 'lift'],
    ['tangga', 'stairs'],
    ['pintu masuk', 'entrance'],
    ['pintu keluar', 'exit'],
    ['kaunter', 'counter'],
    ['taman', 'park / estate'],
    ['bandar', 'town / city'],
    ['kampung', 'village'],
    ['pantai', 'beach'],
    ['di', 'at / in'],
    ['ke', 'to'],
    ['dari', 'from'],
    ['dalam', 'inside'],
    ['luar', 'outside'],
    ['antara', 'between'],
    ['hujung', 'the end of'],
    ['tepi', 'the side of'],
    ['berdekatan', 'nearby']
  ],
  phrases: [
    ['Di mana tandas?', 'Where is the toilet?', 'at where toilet', 'Learn this one cold.'],
    ['Tandas di mana ya?', 'Where are the toilets, please?', 'toilet at where yes', 'ya on the end softens a question into a polite one.'],
    ['Di mana bank yang terdekat?', 'Where is the nearest bank?', 'at where bank which nearest', ''],
    ['Ada farmasi berdekatan?', 'Is there a pharmacy nearby?', 'have pharmacy nearby', ''],
    ['Kedai itu di tingkat berapa?', 'Which floor is that shop on?', 'shop that at floor how-much', ''],
    ['Di tingkat dua.', 'On the second floor.', 'at floor two', ''],
    ['Lif di sebelah sana.', 'The lift is over that way.', 'lift at side there', ''],
    ['Pintu masuk di depan.', 'The entrance is at the front.', 'door enter at front', ''],
    ['Saya cari kedai kopi.', 'I am looking for a coffee shop.', 'I search shop coffee', ''],
    ['Ada di dalam.', 'It is inside.', 'exist at inside', ''],
    ['Tunggu di luar.', 'Wait outside.', 'wait at outside', ''],
    ['Rumah saya dekat stesen.', 'My house is near the station.', 'house my near station', ''],
    ['Saya di sini.', 'I am here.', 'I at here', 'On the phone, this is a whole conversation.'],
    ['Awak di mana sekarang?', 'Where are you now?', 'you at where now', ''],
    ['Saya dalam perjalanan.', 'I am on my way.', 'I inside journey', ''],
    ['Kita jumpa di depan kedai.', 'Let us meet in front of the shop.', 'we meet at front shop', ''],
    ['Tempat ini buka setiap hari?', 'Is this place open every day?', 'place this open every day', ''],
    ['Tutup hari Isnin.', 'Closed on Mondays.', 'closed day Monday', ''],
    ['Jalan ini nama apa?', 'What is this street called?', 'road this name what', ''],
    ['Boleh saya masuk?', 'May I come in?', 'can I enter', '']
  ]
},

/* ============================================================= 10. MASA */
{
  id: 'masa',
  name: 'Time and days',
  malay: 'Masa',
  sub: 'The clock, the week, and when things happen',
  note: 'Malay has no past or future tense. The verb never changes - you add a ' +
        'time word instead. sudah (already) puts it in the past, akan (will) ' +
        'or nanti (later) puts it in the future, sedang (in the middle of) ' +
        'makes it now. "Saya makan" is I eat, I ate and I am eating, and the ' +
        'sentence around it decides which.',
  words: [
    ['masa', 'time'],
    ['jam', 'hour / clock'],
    ['minit', 'minute'],
    ['saat', 'second'],
    ['pukul', 'o clock'],
    ['hari', 'day'],
    ['minggu', 'week'],
    ['bulan', 'month'],
    ['tahun', 'year'],
    ['hari ini', 'today'],
    ['esok', 'tomorrow'],
    ['semalam', 'yesterday'],
    ['lusa', 'the day after tomorrow'],
    ['sekarang', 'now'],
    ['tadi', 'a moment ago'],
    ['nanti', 'later'],
    ['awal', 'early'],
    ['lewat', 'late'],
    ['selalu', 'always / often'],
    ['kadang-kadang', 'sometimes'],
    ['jarang', 'rarely'],
    ['tak pernah', 'never'],
    ['setiap hari', 'every day'],
    ['Isnin', 'Monday'],
    ['Selasa', 'Tuesday'],
    ['Rabu', 'Wednesday'],
    ['Khamis', 'Thursday'],
    ['Jumaat', 'Friday'],
    ['Sabtu', 'Saturday'],
    ['Ahad', 'Sunday'],
    ['hujung minggu', 'weekend'],
    ['cuti', 'holiday / day off'],
    ['sudah', 'already (marks the past)'],
    ['akan', 'will (marks the future)'],
    ['sedang', 'in the middle of'],
    ['belum', 'not yet'],
    ['lepas', 'after'],
    ['sebelum', 'before'],
    ['sejak', 'since'],
    ['hingga', 'until']
  ],
  phrases: [
    ['Pukul berapa sekarang?', 'What time is it?', 'hour how-much now', ''],
    ['Pukul tiga.', 'Three o clock.', 'hour three', ''],
    ['Pukul tiga setengah.', 'Half past three.', 'hour three half', ''],
    ['Pukul tiga suku.', 'Quarter past three.', 'hour three quarter', ''],
    ['Pukul lapan pagi.', 'Eight in the morning.', 'hour eight morning', 'Malay adds pagi, petang or malam rather than using a 24-hour clock.'],
    ['Pukul tujuh malam.', 'Seven in the evening.', 'hour seven night', ''],
    ['Hari ini hari apa?', 'What day is it today?', 'day this day what', ''],
    ['Hari ini hari Rabu.', 'Today is Wednesday.', 'day this day Wednesday', ''],
    ['Bila?', 'When?', '', ''],
    ['Bila awak sampai?', 'When did you get here?', 'when you arrive', 'Also when will you arrive. The context decides.'],
    ['Saya sudah makan.', 'I have eaten.', 'I already eat', 'sudah is the whole past tense.'],
    ['Saya akan datang esok.', 'I will come tomorrow.', 'I will come tomorrow', ''],
    ['Saya sedang kerja.', 'I am working right now.', 'I in-the-middle-of work', ''],
    ['Saya belum makan.', 'I have not eaten yet.', 'I not-yet eat', ''],
    ['Nanti saya telefon.', 'I will call you later.', 'later I telephone', ''],
    ['Sekejap lagi.', 'In a minute.', 'a-moment more', ''],
    ['Lambat sikit.', 'A bit late.', 'late a-little', ''],
    ['Maaf saya lewat.', 'Sorry I am late.', 'sorry I late', ''],
    ['Jam berapa kita jumpa?', 'What time shall we meet?', 'hour how-much we meet', ''],
    ['Hujung minggu ini.', 'This weekend.', 'end week this', ''],
    ['Minggu depan.', 'Next week.', 'week front', 'depan is in front, and in front of now means next.'],
    ['Minggu lepas.', 'Last week.', 'week past', ''],
    ['Setiap hari saya kerja.', 'I work every day.', 'every day I work', ''],
    ['Saya selalu bangun awal.', 'I always get up early.', 'I always wake early', ''],
    ['Kadang-kadang saja.', 'Only sometimes.', 'sometimes only', ''],
    ['Belum lagi.', 'Not yet.', 'not-yet still', ''],
    ['Lepas ini saya balik.', 'After this I am going home.', 'after this I return', '']
  ]
},

/* ============================================================ 11. ORANG */
{
  id: 'orang',
  name: 'People and family',
  malay: 'Orang',
  sub: 'Who is who, and how to address them',
  note: 'Malay pronouns carry social weight. saya is the safe I for everyone. ' +
        'aku is intimate - close friends and family only, and wrong with a ' +
        'stranger. For you, awak is casual, anda is formal and written, kamu ' +
        'is informal, and most of the time the best move is to use no pronoun ' +
        'at all and say abang, kak or makcik instead. dia covers he and she ' +
        'alike, so gender never has to be guessed.',
  words: [
    ['orang', 'person / people'],
    ['saya', 'I (safe everywhere)'],
    ['aku', 'I (intimate only)'],
    ['awak', 'you (casual)'],
    ['anda', 'you (formal)'],
    ['kamu', 'you (informal)'],
    ['dia', 'he / she'],
    ['kita', 'we (including you)'],
    ['kami', 'we (not including you)'],
    ['mereka', 'they'],
    ['keluarga', 'family'],
    ['ibu', 'mother'],
    ['mak', 'mum'],
    ['bapa', 'father'],
    ['ayah', 'dad'],
    ['anak', 'child'],
    ['anak lelaki', 'son'],
    ['anak perempuan', 'daughter'],
    ['suami', 'husband'],
    ['isteri', 'wife'],
    ['abang', 'older brother'],
    ['kakak', 'older sister'],
    ['adik', 'younger sibling'],
    ['nenek', 'grandmother'],
    ['datuk', 'grandfather'],
    ['kawan', 'friend'],
    ['jiran', 'neighbour'],
    ['bos', 'boss'],
    ['lelaki', 'man / male'],
    ['perempuan', 'woman / female'],
    ['budak', 'kid'],
    ['tua', 'old'],
    ['muda', 'young'],
    ['sendiri', 'alone / by oneself'],
    ['bersama', 'together'],
    ['kahwin', 'married'],
    ['bujang', 'single']
  ],
  phrases: [
    ['Ini keluarga saya.', 'This is my family.', 'this family my', ''],
    ['Saya ada dua anak.', 'I have two children.', 'I have two child', ''],
    ['Anak saya umur lima tahun.', 'My child is five.', 'child my age five year', ''],
    ['Awak sudah kahwin?', 'Are you married?', 'you already married', 'A completely normal opening question here.'],
    ['Belum lagi.', 'Not yet.', 'not-yet still', 'The expected answer if you are not. Never just tidak.'],
    ['Saya tinggal dengan keluarga.', 'I live with my family.', 'I live with family', ''],
    ['Dia kawan saya.', 'He is my friend.', 'he friend my', 'dia is he and she both.'],
    ['Siapa itu?', 'Who is that?', 'who that', ''],
    ['Kita pergi sama-sama.', 'Let us go together.', 'we go same-same', 'kita includes the person you are speaking to.'],
    ['Kami dari Singapura.', 'We are from Singapore.', 'we from Singapore', 'kami leaves them out - us, but not you.'],
    ['Mereka belum sampai.', 'They have not arrived.', 'they not-yet arrive', ''],
    ['Saya seorang diri.', 'I am on my own.', 'I one-person self', ''],
    ['Bang, boleh tolong?', 'Excuse me, could you help?', 'brother, can help', 'To a man around your age or a little older.'],
    ['Kak, tanya sikit.', 'Excuse me, a quick question.', 'sister, ask a-little', 'To a woman around your age or a little older.'],
    ['Makcik, berapa ini?', 'Auntie, how much is this?', 'auntie, how-much this', 'To an older woman. Warm, not rude.'],
    ['Encik nak ke mana?', 'Where are you going, sir?', 'sir want to where', ''],
    ['Anak siapa ini?', 'Whose child is this?', 'child who this', ''],
    ['Dia orang baik.', 'He is a good person.', 'he person good', ''],
    ['Saya kenal dia.', 'I know him.', 'I know him', 'kenal is knowing a person. tahu is knowing a fact.'],
    ['Saya tak kenal.', 'I do not know them.', 'I not know-person', '']
  ]
},

/* ============================================================ 12. BADAN */
{
  id: 'badan',
  name: 'Health and the body',
  malay: 'Badan',
  sub: 'Saying what hurts, and getting help',
  note: 'sakit is the workhorse: it means ill, and it means painful, and you ' +
        'point it at a body part to say where. sakit kepala is head pain, ' +
        'sakit perut is stomach pain. The thing comes first, the complaint ' +
        'after - the same word order as nasi goreng.',
  words: [
    ['badan', 'body'],
    ['sakit', 'ill / painful'],
    ['sihat', 'healthy'],
    ['kepala', 'head'],
    ['mata', 'eye'],
    ['telinga', 'ear'],
    ['hidung', 'nose'],
    ['mulut', 'mouth'],
    ['gigi', 'tooth'],
    ['leher', 'neck'],
    ['tangan', 'hand / arm'],
    ['kaki', 'foot / leg'],
    ['perut', 'stomach'],
    ['belakang', 'back'],
    ['dada', 'chest'],
    ['darah', 'blood'],
    ['demam', 'fever'],
    ['batuk', 'cough'],
    ['selsema', 'a cold'],
    ['muntah', 'to vomit'],
    ['pening', 'dizzy'],
    ['letih', 'tired'],
    ['penat', 'worn out'],
    ['luka', 'a cut / wound'],
    ['ubat', 'medicine'],
    ['doktor', 'doctor'],
    ['jururawat', 'nurse'],
    ['hospital', 'hospital'],
    ['klinik', 'clinic'],
    ['farmasi', 'pharmacy'],
    ['ambulans', 'ambulance'],
    ['alahan', 'allergy'],
    ['rehat', 'rest'],
    ['tidur', 'sleep'],
    ['bangun', 'wake up'],
    ['baik', 'better / recovered'],
    ['teruk', 'bad / severe']
  ],
  phrases: [
    ['Saya sakit.', 'I am ill.', 'I ill', ''],
    ['Saya tak sihat.', 'I am not well.', 'I not healthy', ''],
    ['Saya sakit kepala.', 'I have a headache.', 'I pain head', ''],
    ['Saya sakit perut.', 'I have a stomach ache.', 'I pain stomach', ''],
    ['Sakit di sini.', 'It hurts here.', 'pain at here', 'Point as you say it. Fastest sentence in the unit.'],
    ['Saya demam.', 'I have a fever.', 'I fever', ''],
    ['Saya batuk.', 'I have a cough.', 'I cough', ''],
    ['Saya selsema.', 'I have a cold.', 'I cold', ''],
    ['Saya rasa pening.', 'I feel dizzy.', 'I feel dizzy', ''],
    ['Saya sangat letih.', 'I am very tired.', 'I very tired', ''],
    ['Sudah berapa lama?', 'How long has it been?', 'already how-much long', 'What the doctor will ask you.'],
    ['Dua hari sudah.', 'Two days now.', 'two day already', ''],
    ['Saya perlu jumpa doktor.', 'I need to see a doctor.', 'I need meet doctor', ''],
    ['Klinik di mana?', 'Where is the clinic?', 'clinic at where', ''],
    ['Tolong panggil ambulans!', 'Please call an ambulance!', 'please call ambulance', ''],
    ['Ada ubat untuk batuk?', 'Do you have something for a cough?', 'have medicine for cough', 'At the pharmacy counter.'],
    ['Berapa kali sehari?', 'How many times a day?', 'how-much time a-day', 'About the dosage.'],
    ['Saya ada alahan kepada kacang.', 'I am allergic to nuts.', 'I have allergy toward nut', ''],
    ['Saya tak boleh makan ini.', 'I cannot eat this.', 'I not can eat this', ''],
    ['Saya perlu rehat.', 'I need to rest.', 'I need rest', ''],
    ['Sudah baik sikit.', 'A bit better now.', 'already good a-little', ''],
    ['Jaga diri.', 'Look after yourself.', 'guard self', '']
  ]
},

/* ============================================================= 13. RASA */
{
  id: 'rasa',
  name: 'Feelings and opinions',
  malay: 'Rasa',
  sub: 'Liking, wanting, thinking and complaining',
  note: 'rasa means both to feel and to taste, and it also means to reckon - ' +
        '"saya rasa" is I think. To make something stronger, put sangat before ' +
        'it or tack -lah on the end. To say too much of something, put ter- in ' +
        'front: terlalu mahal, tersalah, terlambat.',
  words: [
    ['rasa', 'feel / taste / think'],
    ['suka', 'like'],
    ['tak suka', 'dislike'],
    ['sayang', 'love / what a pity'],
    ['benci', 'hate'],
    ['gembira', 'happy'],
    ['sedih', 'sad'],
    ['marah', 'angry'],
    ['takut', 'afraid'],
    ['risau', 'worried'],
    ['seronok', 'fun / enjoyable'],
    ['bosan', 'bored'],
    ['penat', 'tired out'],
    ['lega', 'relieved'],
    ['terkejut', 'surprised'],
    ['malu', 'embarrassed / shy'],
    ['sibuk', 'busy'],
    ['lapang', 'free / unoccupied'],
    ['senang', 'easy / at ease'],
    ['susah', 'difficult'],
    ['penting', 'important'],
    ['menarik', 'interesting'],
    ['cantik', 'beautiful'],
    ['kacak', 'handsome'],
    ['comel', 'cute'],
    ['hebat', 'amazing'],
    ['teruk', 'awful'],
    ['biasa', 'ordinary / usual'],
    ['pelik', 'strange'],
    ['fikir', 'think'],
    ['harap', 'hope'],
    ['setuju', 'agree'],
    ['sangat', 'very'],
    ['terlalu', 'too / excessively'],
    ['sedikit', 'slightly'],
    ['mungkin', 'maybe'],
    ['memang', 'indeed / genuinely'],
    ['betul-betul', 'really']
  ],
  phrases: [
    ['Saya suka.', 'I like it.', 'I like', ''],
    ['Saya suka sangat!', 'I really like it!', 'I like very', ''],
    ['Saya tak suka.', 'I do not like it.', 'I not like', ''],
    ['Saya rasa boleh.', 'I think that works.', 'I think can', ''],
    ['Saya rasa tak boleh.', 'I do not think so.', 'I think not can', ''],
    ['Pada pendapat saya...', 'In my opinion...', 'at opinion my', 'The formal opener, for meetings.'],
    ['Saya setuju.', 'I agree.', 'I agree', ''],
    ['Saya tak setuju.', 'I do not agree.', 'I not agree', ''],
    ['Seronoknya!', 'What fun!', 'fun-the', 'Adding -nya to a feeling turns it into an exclamation.'],
    ['Cantiknya!', 'How lovely!', 'beautiful-the', ''],
    ['Saya penat sangat.', 'I am worn out.', 'I tired very', ''],
    ['Saya sibuk hari ini.', 'I am busy today.', 'I busy day this', ''],
    ['Saya bosan.', 'I am bored.', 'I bored', ''],
    ['Saya risau sikit.', 'I am a little worried.', 'I worried a-little', ''],
    ['Jangan marah.', 'Do not be cross.', 'do-not angry', ''],
    ['Susah sikit.', 'It is a bit hard.', 'difficult a-little', ''],
    ['Senang saja.', 'It is easy.', 'easy only', ''],
    ['Terlalu mahal.', 'Too expensive.', 'too expensive', ''],
    ['Menarik!', 'Interesting!', '', ''],
    ['Sayang sekali.', 'What a shame.', 'pity once', ''],
    ['Tak apa, biasa saja.', 'It is fine, nothing unusual.', 'no-matter, ordinary only', ''],
    ['Memang betul.', 'That is quite true.', 'indeed true', ''],
    ['Mungkin esok.', 'Maybe tomorrow.', 'maybe tomorrow', ''],
    ['Apa pendapat awak?', 'What do you think?', 'what opinion your', '']
  ]
},

/* =========================================================== 14. HARIAN */
{
  id: 'harian',
  name: 'Daily life',
  malay: 'Harian',
  sub: 'Weather, the house, and what you did today',
  note: 'Weather is one pattern: hari ini panas, hari ini hujan - today hot, ' +
        'today rain. No it, no is. And a doubled noun is the nearest Malay ' +
        'gets to a plural: barang-barang (things), kawan-kawan (friends). ' +
        'You never need it after a number.',
  words: [
    ['hari', 'day'],
    ['cuaca', 'weather'],
    ['panas', 'hot'],
    ['sejuk', 'cold / cool'],
    ['hujan', 'rain'],
    ['ribut', 'storm'],
    ['angin', 'wind'],
    ['matahari', 'sun'],
    ['awan', 'cloud'],
    ['basah', 'wet'],
    ['kering', 'dry'],
    ['payung', 'umbrella'],
    ['rumah', 'house'],
    ['bilik tidur', 'bedroom'],
    ['dapur', 'kitchen'],
    ['tingkap', 'window'],
    ['pintu', 'door'],
    ['lampu', 'light'],
    ['kipas', 'fan'],
    ['air-cond', 'air conditioning'],
    ['katil', 'bed'],
    ['meja', 'table'],
    ['kerusi', 'chair'],
    ['bangun', 'get up'],
    ['mandi', 'to shower / bathe'],
    ['gosok gigi', 'brush teeth'],
    ['masak', 'to cook'],
    ['basuh', 'to wash'],
    ['cuci', 'to clean / wash'],
    ['kemas', 'to tidy'],
    ['sapu', 'to sweep'],
    ['buang sampah', 'take the rubbish out'],
    ['beli-belah', 'to do the shopping'],
    ['rehat', 'to rest'],
    ['tengok TV', 'watch TV'],
    ['telefon', 'phone / to call'],
    ['mesej', 'message'],
    ['keluar', 'go out'],
    ['masuk', 'go in'],
    ['siap', 'ready / finished']
  ],
  phrases: [
    ['Hari ini panas.', 'It is hot today.', 'day this hot', 'No it and no is. This is the whole sentence.'],
    ['Panas sangat hari ini!', 'It is so hot today!', 'hot very day this', ''],
    ['Hari ini hujan.', 'It is raining today.', 'day this rain', ''],
    ['Nanti hujan.', 'It is going to rain.', 'later rain', ''],
    ['Bawa payung.', 'Take an umbrella.', 'bring umbrella', ''],
    ['Sejuk di dalam.', 'It is cold inside.', 'cold at inside', ''],
    ['Boleh tutup air-cond?', 'Could you turn the aircon off?', 'can close air-cond', 'Malay opens and closes things that English switches on and off.'],
    ['Boleh buka tingkap?', 'Could you open the window?', 'can open window', ''],
    ['Tolong tutup pintu.', 'Please close the door.', 'please close door', ''],
    ['Saya bangun pukul tujuh.', 'I get up at seven.', 'I wake hour seven', ''],
    ['Saya nak mandi dulu.', 'I am going to shower first.', 'I want bathe first', ''],
    ['Saya masak sendiri.', 'I cook for myself.', 'I cook self', ''],
    ['Saya nak keluar sekejap.', 'I am popping out.', 'I want exit a-moment', ''],
    ['Saya dah siap.', 'I am ready.', 'I already ready', ''],
    ['Belum siap lagi.', 'Not ready yet.', 'not-yet ready still', ''],
    ['Saya penat, nak tidur.', 'I am tired, I want to sleep.', 'I tired, want sleep', ''],
    ['Rumah saya kecil saja.', 'My place is small.', 'house my small only', ''],
    ['Banyak kerja rumah hari ini.', 'Lots of housework today.', 'many work house day this', ''],
    ['Saya kena buang sampah.', 'I have to take the rubbish out.', 'I must throw rubbish', 'kena is have to, and it is everywhere in speech.'],
    ['Nanti saya mesej awak.', 'I will message you later.', 'later I message you', ''],
    ['Barang-barang saya di dalam.', 'My things are inside.', 'thing-thing my at inside', 'The doubled noun is how you say more than one.']
  ]
},

/* ============================================================ 15. KERJA */
{
  id: 'kerja',
  name: 'Work and study',
  malay: 'Kerja',
  sub: 'The office, the shift, and getting things done',
  note: 'Malay builds new words with prefixes rather than new roots. From ' +
        'kerja (work) you get pekerja (a worker) and bekerja (to be working); ' +
        'from ajar (teach) you get pengajar (teacher) and belajar (to study). ' +
        'Spotting the root inside a long word is most of reading Malay.',
  words: [
    ['kerja', 'work / job'],
    ['bekerja', 'to work'],
    ['pekerja', 'worker / staff'],
    ['pejabat', 'office'],
    ['syarikat', 'company'],
    ['bos', 'boss'],
    ['rakan sekerja', 'colleague'],
    ['pelanggan', 'customer'],
    ['mesyuarat', 'meeting'],
    ['projek', 'project'],
    ['tugas', 'task / duty'],
    ['laporan', 'report'],
    ['e-mel', 'email'],
    ['gaji', 'salary'],
    ['cuti', 'leave / holiday'],
    ['syif', 'shift'],
    ['lebih masa', 'overtime'],
    ['mula', 'to start'],
    ['habis', 'to finish'],
    ['siap', 'completed'],
    ['hantar', 'to send / deliver'],
    ['terima', 'to receive'],
    ['tolong', 'to help'],
    ['buat', 'to do / make'],
    ['guna', 'to use'],
    ['cari', 'to look for'],
    ['jumpa', 'to meet / find'],
    ['tunggu', 'to wait'],
    ['sedia', 'ready'],
    ['sekolah', 'school'],
    ['universiti', 'university'],
    ['pelajar', 'student'],
    ['cikgu', 'teacher'],
    ['kelas', 'class'],
    ['buku', 'book'],
    ['peperiksaan', 'exam'],
    ['latihan', 'practice / training'],
    ['kursus', 'course'],
    ['penting', 'important'],
    ['cepat', 'quick']
  ],
  phrases: [
    ['Saya kerja di syarikat kecil.', 'I work at a small company.', 'I work at company small', ''],
    ['Saya kerja dari rumah.', 'I work from home.', 'I work from house', ''],
    ['Pukul berapa awak mula kerja?', 'What time do you start?', 'hour how-much you start work', ''],
    ['Saya habis kerja pukul enam.', 'I finish at six.', 'I finish work hour six', ''],
    ['Saya ada mesyuarat.', 'I have a meeting.', 'I have meeting', ''],
    ['Saya sibuk sekarang.', 'I am busy right now.', 'I busy now', ''],
    ['Boleh tunggu sekejap?', 'Could you wait a moment?', 'can wait a-moment', ''],
    ['Saya akan hantar e-mel.', 'I will send an email.', 'I will send email', ''],
    ['Sudah siap.', 'It is done.', 'already complete', ''],
    ['Belum siap lagi.', 'Not finished yet.', 'not-yet complete still', ''],
    ['Bila nak siap?', 'When will it be ready?', 'when want complete', ''],
    ['Saya buat esok.', 'I will do it tomorrow.', 'I do tomorrow', ''],
    ['Tolong buat cepat sikit.', 'Please do it a bit faster.', 'please do fast a-little', ''],
    ['Saya kena buat lebih masa.', 'I have to work overtime.', 'I must do over time', ''],
    ['Saya ambil cuti esok.', 'I am taking tomorrow off.', 'I take leave tomorrow', ''],
    ['Bos saya baik.', 'My boss is decent.', 'boss my good', ''],
    ['Ini tugas siapa?', 'Whose job is this?', 'this task who', ''],
    ['Saya tak berapa faham.', 'I do not quite follow.', 'I not how-much understand', 'tak berapa is the polite not-really.'],
    ['Boleh terangkan lagi?', 'Could you explain that again?', 'can explain again', ''],
    ['Saya belajar di universiti.', 'I study at university.', 'I study at university', ''],
    ['Kelas mula pukul lapan.', 'Class starts at eight.', 'class start hour eight', ''],
    ['Saya ada peperiksaan minggu depan.', 'I have an exam next week.', 'I have exam week front', '']
  ]
},

/* ========================================================== 16. MASALAH */
{
  id: 'masalah',
  name: 'When things go wrong',
  malay: 'Masalah',
  sub: 'Lost, stuck, or needing help fast',
  note: 'In an emergency, short wins. tolong is help. sakit is hurt. hilang ' +
        'is lost or missing. polis is police. Strung together with nothing ' +
        'else at all, those words work: "Tolong! Beg saya hilang!"',
  words: [
    ['masalah', 'problem'],
    ['tolong', 'help'],
    ['bahaya', 'danger'],
    ['kecemasan', 'emergency'],
    ['polis', 'police'],
    ['bomba', 'fire brigade'],
    ['kebakaran', 'a fire'],
    ['kemalangan', 'accident'],
    ['hilang', 'lost / missing'],
    ['curi', 'to steal'],
    ['pencuri', 'thief'],
    ['jatuh', 'to fall'],
    ['pecah', 'broken / shattered'],
    ['rosak', 'broken down'],
    ['terkunci', 'locked out'],
    ['lupa', 'to forget'],
    ['tertinggal', 'left behind'],
    ['salah', 'wrong / mistake'],
    ['tersalah', 'by mistake'],
    ['dompet', 'wallet'],
    ['pasport', 'passport'],
    ['telefon bimbit', 'mobile phone'],
    ['kunci', 'key'],
    ['beg', 'bag'],
    ['duit', 'money'],
    ['laporan polis', 'police report'],
    ['insurans', 'insurance'],
    ['kedutaan', 'embassy'],
    ['cepat', 'quickly'],
    ['bahasa Inggeris', 'English'],
    ['faham', 'to understand'],
    ['ulang', 'to repeat'],
    ['perlahan', 'slowly']
  ],
  phrases: [
    ['Tolong!', 'Help!', '', ''],
    ['Ada kecemasan!', 'There is an emergency!', 'exist emergency', ''],
    ['Panggil polis!', 'Call the police!', 'call police', ''],
    ['Panggil ambulans!', 'Call an ambulance!', 'call ambulance', ''],
    ['Ada kemalangan.', 'There has been an accident.', 'exist accident', ''],
    ['Beg saya hilang.', 'My bag is missing.', 'bag my lost', ''],
    ['Dompet saya kena curi.', 'My wallet has been stolen.', 'wallet my suffer steal', 'kena before a verb is how Malay makes the passive in speech.'],
    ['Pasport saya hilang.', 'I have lost my passport.', 'passport my lost', ''],
    ['Saya tertinggal telefon.', 'I have left my phone behind.', 'I left-behind phone', ''],
    ['Saya terkunci di luar.', 'I am locked out.', 'I locked at outside', ''],
    ['Saya sesat.', 'I am lost.', 'I lost', ''],
    ['Saya tak jumpa jalan.', 'I cannot find the way.', 'I not find road', ''],
    ['Telefon saya rosak.', 'My phone is broken.', 'phone my broken', ''],
    ['Kereta saya rosak.', 'My car has broken down.', 'car my broken', ''],
    ['Saya nak buat laporan polis.', 'I want to make a police report.', 'I want make report police', ''],
    ['Balai polis di mana?', 'Where is the police station?', 'station police at where', ''],
    ['Saya perlu hubungi kedutaan.', 'I need to contact my embassy.', 'I need contact embassy', ''],
    ['Ada sesiapa cakap Inggeris?', 'Does anyone speak English?', 'exist anyone speak English', ''],
    ['Saya tak faham. Tolong perlahan.', 'I do not understand. Slowly, please.', 'I not understand. please slow', ''],
    ['Boleh ulang sekali lagi?', 'Could you say that once more?', 'can repeat once more', ''],
    ['Saya tersalah.', 'I made a mistake.', 'I by-mistake', ''],
    ['Bukan saya.', 'It was not me.', 'not me', 'bukan, not tak - it is denying a noun.'],
    ['Tolong saya sikit.', 'Please help me out.', 'help me a-little', '']
  ]
},

/* ============================================================= 17. AYAT */
{
  id: 'ayat',
  name: 'Making your own sentences',
  malay: 'Ayat',
  sub: 'The patterns everything else is built from',
  note: 'This unit is the grammar, and there is not much of it. Swap the word ' +
        'in bold and each pattern becomes a hundred sentences. The one rule ' +
        'worth memorising outright: tak negates a verb or a description, ' +
        'bukan negates a noun. Saya tak lapar (I am not hungry) but Ini bukan ' +
        'teh (this is not tea).',
  words: [
    ['yang', 'which / the one that'],
    ['untuk', 'for'],
    ['dengan', 'with / by'],
    ['sebab', 'because'],
    ['kalau', 'if'],
    ['tapi', 'but'],
    ['dan', 'and'],
    ['atau', 'or'],
    ['macam', 'like / as'],
    ['sampai', 'until'],
    ['lepas', 'after'],
    ['sebelum', 'before'],
    ['kena', 'must / have to'],
    ['perlu', 'need to'],
    ['patut', 'ought to'],
    ['pernah', 'have ever'],
    ['masih', 'still'],
    ['pun', 'even / too'],
    ['lagi', 'more / again'],
    ['sendiri', 'oneself'],
    ['semua', 'all'],
    ['setiap', 'every'],
    ['apa-apa', 'anything'],
    ['sesiapa', 'anyone'],
    ['di mana-mana', 'anywhere'],
    ['ter-', 'accidentally / most'],
    ['-lah', 'softener / emphasis'],
    ['-kah', 'question marker'],
    ['-nya', 'the / its']
  ],
  phrases: [
    ['Saya nak _____.', 'I want to _____.', 'I want ...', 'Fill in any verb: makan, pergi, balik, tidur. The backbone of asking for things.'],
    ['Boleh _____ tak?', 'Can I / you _____?', 'can ... not', 'Boleh tolong tak? Boleh masuk tak? Adding tak makes it a yes-or-no question.'],
    ['Ada _____?', 'Do you have _____?', 'exist ...', 'Ada teh? Ada saiz besar? Ada orang? Half of shopping is this one word.'],
    ['Di mana _____?', 'Where is _____?', 'at where ...', 'Di mana tandas? Di mana stesen?'],
    ['Berapa _____?', 'How much _____?', 'how-much ...', 'Berapa harga? Berapa lama? Berapa orang?'],
    ['Saya tak _____.', 'I do not _____.', 'I not ...', 'For verbs and descriptions: tak tahu, tak faham, tak lapar.'],
    ['Ini bukan _____.', 'This is not _____.', 'this not ...', 'For nouns only. Ini bukan teh. Bukan saya. Never tak here.'],
    ['Saya kena _____.', 'I have to _____.', 'I must ...', 'kena is the spoken must. Saya kena pergi. Saya kena bayar.'],
    ['Jangan _____.', 'Do not _____.', "don't ...", 'Jangan pergi. Jangan risau. Jangan lupa.'],
    ['Tolong _____.', 'Please _____.', 'help ...', 'Tolong tutup pintu. Tolong bagi resit. Softer than a bare order.'],
    ['_____ untuk saya.', '_____ for me.', '... for me', 'Satu untuk saya. Ini untuk awak.'],
    ['Saya pergi dengan kawan.', 'I am going with a friend.', 'I go with friend', 'dengan is with, and also by - dengan bas, by bus.'],
    ['Sebab saya penat.', 'Because I am tired.', 'because I tired', ''],
    ['Kalau hujan, saya tak pergi.', 'If it rains, I will not go.', 'if rain, I not go', 'No tense anywhere. kalau does the work.'],
    ['Sedap tapi mahal.', 'Tasty but expensive.', 'delicious but expensive', ''],
    ['Yang ini atau yang itu?', 'This one or that one?', 'which this or which that', 'yang turns anything into the one that - yang merah, the red one.'],
    ['Saya nak yang murah.', 'I want the cheap one.', 'I want which cheap', ''],
    ['Awak pernah pergi Melaka?', 'Have you ever been to Melaka?', 'you ever go Melaka', 'pernah is the have-you-ever word.'],
    ['Saya masih belajar.', 'I am still learning.', 'I still study', ''],
    ['Saya pun sama.', 'Me too.', 'I also same', ''],
    ['Makanlah.', 'Do eat.', 'eat-lah', '-lah softens an order into an invitation. It is the single most Malaysian syllable there is.'],
    ['Besar sangat pula.', 'That is rather too big.', 'big very moreover', ''],
    ['Apa-apa pun boleh.', 'Anything is fine.', 'anything even can', ''],
    ['Semua orang tahu.', 'Everybody knows.', 'all person know', '']
  ]
},

/* =========================================================== 18. DI RUMAH
   A kept section rather than a taught one - the phrases that actually come up
   at home, day after day, between the people living and working in it. Your
   own additions land at the bottom of this list and are saved on the device.

   Plenty of households here speak Indonesian rather than Malay, and a handful
   of everyday words genuinely differ. Where they do, the Indonesian is given
   as a fifth field and the app shows it under the Malay.                    */
{
  id: 'rumah',
  name: 'At home',
  malay: 'Di Rumah',
  sub: 'Cooking, cleaning and the day-to-day, at home',
  featured: true,
  custom: true,
  note: 'Two words make an instruction sound like a request rather than an ' +
        'order, and both are worth the half second they cost. tolong in front ' +
        'means please - tolong masak, tolong cuci. boleh in front turns it ' +
        'into a question - boleh tolong masak? Bare verbs are not rude in ' +
        'Malay, but tolong is warmer, and it is what you will hear back. ' +
        'One more thing worth knowing: if the person you are speaking with is ' +
        'Indonesian rather than Malaysian, a few everyday words differ - bisa ' +
        'instead of boleh, mau instead of nak, tidak or nggak instead of tak. ' +
        'Those are shown underneath where they matter. The grammar is the same.',
  words: [
    ['tolong', 'please / help'],
    ['masak', 'to cook'],
    ['masakan', 'cooking / a dish'],
    ['makan', 'to eat / food'],
    ['makanan', 'food'],
    ['sarapan', 'breakfast'],
    ['makan tengah hari', 'lunch'],
    ['makan malam', 'dinner'],
    ['dapur', 'kitchen'],
    ['peti sejuk', 'fridge'],
    ['sayur', 'vegetables'],
    ['daging', 'meat'],
    ['ayam', 'chicken'],
    ['ikan', 'fish'],
    ['nasi', 'rice'],
    ['telur', 'egg'],
    ['garam', 'salt'],
    ['gula', 'sugar'],
    ['minyak', 'oil'],
    ['panaskan', 'to heat up'],
    ['potong', 'to cut'],
    ['cuci', 'to wash'],
    ['basuh', 'to wash (clothes)'],
    ['kemas', 'to tidy'],
    ['sapu', 'to sweep'],
    ['mop', 'to mop'],
    ['lap', 'to wipe'],
    ['sampah', 'rubbish'],
    ['baju', 'clothes'],
    ['seluar', 'trousers'],
    ['tuala', 'towel'],
    ['cadar', 'bedsheet'],
    ['mesin basuh', 'washing machine'],
    ['sidai', 'to hang out to dry'],
    ['lipat', 'to fold'],
    ['gosok', 'to iron'],
    ['bilik', 'room'],
    ['tingkap', 'window'],
    ['lantai', 'floor'],
    ['tandas', 'toilet'],
    ['beli', 'to buy'],
    ['habis', 'run out / finished'],
    ['simpan', 'to keep / put away'],
    ['buang', 'to throw out'],
    ['jaga', 'to look after'],
    ['anak', 'child'],
    ['sekolah', 'school'],
    ['cuti', 'day off'],
    ['rehat', 'rest'],
    ['balik', 'to go back'],
    ['nanti', 'later'],
    ['dulu', 'first'],
    ['siap', 'done / ready'],
    ['jangan', 'do not'],
    ['hati-hati', 'be careful']
  ],
  phrases: [
    ['Tolong masakkan sesuatu.', 'Please cook something.', 'please cook-for something', 'The -kan on the end means do it for someone. Softer than a bare tolong masak.', 'Tolong masakin sesuatu.'],
    ['Saya tak tahu.', 'I do not know.', 'I not know', '', 'Saya tidak tahu. / Saya nggak tahu.'],
    ['Ada apa nak makan?', 'What is there to eat?', 'exist what want eat', 'The everyday way to ask what food is in the house.', 'Ada apa mau makan?'],

    ['Boleh tolong masak?', 'Could you cook, please?', 'can help cook', 'boleh in front turns an instruction into a question.', 'Bisa tolong masak?'],
    ['Masak apa hari ini?', 'What are you cooking today?', 'cook what day this', '', ''],
    ['Masak apa-apa pun boleh.', 'Anything is fine.', 'cook anything even can', '', 'Masak apa aja boleh.'],
    ['Saya nak makan nasi ayam.', 'I would like chicken rice.', 'I want eat rice chicken', '', 'Saya mau makan nasi ayam.'],
    ['Jangan pedas sangat.', 'Not too spicy, please.', 'do-not spicy very', '', 'Jangan terlalu pedas.'],
    ['Kurang garam sikit.', 'A little less salt.', 'less salt a-little', '', 'Kurangin garamnya sedikit.'],
    ['Tolong panaskan makanan.', 'Please heat the food up.', 'please heat food', '', 'Tolong panasin makanannya.'],
    ['Masak untuk berapa orang?', 'Cooking for how many?', 'cook for how-much person', '', ''],
    ['Untuk empat orang.', 'For four people.', 'for four person', '', ''],
    ['Sarapan pukul lapan.', 'Breakfast at eight.', 'breakfast hour eight', '', ''],
    ['Makan malam pukul tujuh.', 'Dinner at seven.', 'eat night hour seven', '', ''],
    ['Saya makan di luar malam ini.', 'I am eating out tonight.', 'I eat at outside night this', '', ''],
    ['Tak payah masak untuk saya.', 'No need to cook for me.', 'no-need cook for me', '', 'Nggak usah masak buat saya.'],
    ['Simpan dalam peti sejuk.', 'Put it in the fridge.', 'keep inside box cold', '', 'Simpan di kulkas.'],
    ['Sedap sangat, terima kasih.', 'That was lovely, thank you.', 'delicious very, thank you', 'Worth saying out loud. It costs nothing.', ''],

    ['Tolong cuci pinggan.', 'Please wash the dishes.', 'please wash plate', '', 'Tolong cuci piring.'],
    ['Tolong kemas bilik.', 'Please tidy the room.', 'please tidy room', '', 'Tolong rapikan kamar.'],
    ['Tolong sapu lantai.', 'Please sweep the floor.', 'please sweep floor', '', ''],
    ['Tolong mop lantai.', 'Please mop the floor.', 'please mop floor', '', 'Tolong pel lantai.'],
    ['Tolong lap meja.', 'Please wipe the table.', 'please wipe table', '', ''],
    ['Tolong buang sampah.', 'Please take the rubbish out.', 'please throw rubbish', '', ''],
    ['Tolong basuh baju.', 'Please do the laundry.', 'please wash clothes', '', 'Tolong cuci baju.'],
    ['Tolong sidai baju.', 'Please hang the washing out.', 'please hang clothes', '', 'Tolong jemur baju.'],
    ['Tolong lipat baju.', 'Please fold the clothes.', 'please fold clothes', '', ''],
    ['Tolong gosok baju ini.', 'Please iron these.', 'please iron clothes this', '', 'Tolong setrika baju ini.'],
    ['Tolong tukar cadar.', 'Please change the bedsheets.', 'please change bedsheet', '', 'Tolong ganti seprai.'],
    ['Tolong cuci tandas.', 'Please clean the toilet.', 'please wash toilet', '', 'Tolong bersihin kamar mandi.'],
    ['Nanti saja, tak apa.', 'Later is fine.', 'later only, no-matter', '', 'Nanti aja, nggak apa-apa.'],
    ['Buat ini dulu.', 'Do this one first.', 'do this first', '', ''],
    ['Tak payah buat hari ini.', 'No need to do it today.', 'no-need do day this', '', 'Nggak usah dikerjain hari ini.'],

    ['Barang dah habis.', 'We have run out.', 'thing already finished', '', 'Barangnya sudah habis.'],
    ['Apa yang dah habis?', 'What have we run out of?', 'what which already finished', '', ''],
    ['Tolong beli sayur.', 'Please buy vegetables.', 'please buy vegetable', '', ''],
    ['Ini duit untuk beli barang.', 'Here is money for the shopping.', 'this money for buy things', '', 'Ini uang buat belanja.'],
    ['Simpan resit ya.', 'Keep the receipt please.', 'keep receipt yes', '', ''],
    ['Baki simpan saja.', 'Keep the change.', 'change keep only', '', 'Kembaliannya simpan aja.'],

    ['Tolong jaga anak.', 'Please look after the children.', 'please guard child', '', ''],
    ['Hantar dia ke sekolah.', 'Take him to school.', 'send him to school', '', 'Antar dia ke sekolah.'],
    ['Ambil dia pukul tiga.', 'Pick her up at three.', 'take her hour three', '', 'Jemput dia jam tiga.'],
    ['Jangan bagi dia gula-gula.', 'Do not give him sweets.', 'do-not give him sweets', '', 'Jangan kasih dia permen.'],

    ['Hari ini awak cuti.', 'You have the day off today.', 'day this you holiday', '', 'Hari ini kamu libur.'],
    ['Awak boleh rehat.', 'You can rest.', 'you can rest', '', 'Kamu bisa istirahat.'],
    ['Ahad awak cuti.', 'Sunday is your day off.', 'Sunday you holiday', '', 'Minggu kamu libur.'],
    ['Awak balik pukul berapa?', 'What time will you be back?', 'you return hour how-much', '', 'Kamu pulang jam berapa?'],
    ['Saya balik lewat malam ini.', 'I will be back late tonight.', 'I return late night this', '', 'Saya pulang telat malam ini.'],
    ['Awak dah makan?', 'Have you eaten?', 'you already eat', 'Asked as a kindness, not a question about food. It is the warmest thing on this list.', 'Kamu sudah makan?'],
    ['Awak sihat?', 'Are you feeling alright?', 'you healthy', '', 'Kamu sehat?'],
    ['Kalau sakit, beritahu saya.', 'If you are unwell, tell me.', 'if ill, tell me', '', 'Kalau sakit, bilang saya.'],

    ['Boleh ulang? Saya tak faham.', 'Say that again? I did not catch it.', 'can repeat, I not understand', '', 'Bisa diulang? Saya nggak ngerti.'],
    ['Awak faham?', 'Do you understand?', 'you understand', '', 'Kamu ngerti?'],
    ['Tanya saya kalau tak pasti.', 'Ask me if you are not sure.', 'ask me if not certain', '', 'Tanya saya kalau nggak yakin.'],
    ['Tak apa, jangan risau.', 'It is alright, do not worry.', 'no-matter, do-not worry', 'For when something gets broken. It matters more than the thing did.', 'Nggak apa-apa, jangan khawatir.'],
    ['Hati-hati ya.', 'Be careful.', 'careful yes', '', ''],
    ['Terima kasih banyak.', 'Thank you very much.', 'thank you many', '', ''],
    ['Kerja awak bagus.', 'You have done a good job.', 'work your good', '', 'Kerja kamu bagus.']
  ]
}

];
